//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DB_assingnment_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string project_name { get; set; }
        public int Budget { get; set; }
        public string project_no { get; set; }
    }
}