//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DB_assingnment_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works_on
    {
        public int emp_no { get; set; }
        public string project_no { get; set; }
        public string Job { get; set; }
        public System.DateTime enter_date { get; set; }
    }
}